/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Siswa, TransaksiKas, WhatsAppLog, WhatsAppConfig } from './types';

export const ACADEMIC_MONTHS = [
  'Juli 2026',
  'Agustus 2026',
  'September 2026',
  'Oktober 2026',
  'November 2026',
  'Desember 2026',
  'Januari 2027',
  'Februari 2027',
  'Maret 2027',
  'April 2027',
  'Mei 2027',
  'Juni 2027',
];

export const LIST_KELAS = ['1-A', '1-B', '2-A', '2-B', '3-A', '3-B', '4-A', '4-B', '5-A', '5-B', '6-A', '6-B'];

export const KATEGORI_PEMASUKAN = [
  'SPP Bulanan',
  'Uang Gedung / Pendaftaran',
  'Uang Kegiatan Siswa',
  'Donasi / Infaq',
  'Dana BOS',
  'Pemasukan Lainnya',
];

export const KATEGORI_PENGELUARAN = [
  'Gaji Guru & Staff',
  'Operasional Listrik & Wifi',
  'ATK & Kebutuhan Kantor',
  'Pemeliharaan Gedung & Sarpras',
  'Biaya Kegiatan & Lomba',
  'Konsumsi Rapat / Harian',
  'Pengeluaran Lainnya',
];

export const DEFAULT_WA_CONFIG: WhatsAppConfig = {
  apiKey: 'ALFATIH_GATEWAY_SECURE_TOKEN_XYZ888',
  senderNumber: '6281234567890',
  isConnected: true,
  gateway: 'Simulasi',
};

export const INITIAL_SISWA: Siswa[] = [
  {
    id: 's1',
    nis: '20261001',
    nama: 'Ahmad Rafif Al-Fatih',
    kelas: '3-A',
    namaOrangTua: 'Hendra Wijaya',
    noWhatsApp: '6281273849201',
    alamat: 'Perumahan Bukit Indah Blok C-12, Baturaja',
    nominalSPP: 250000,
    tanggalLahir: '12-05-2015',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-05', transactionId: 't-spp1' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-04', transactionId: 't-spp2' },
      'September 2026': { paid: false },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's2',
    nis: '20261002',
    nama: 'Aisyah Humaira',
    kelas: '3-A',
    namaOrangTua: 'Budi Santoso',
    noWhatsApp: '6281367895432',
    alamat: 'Jl. Melati No. 45 RT 02, Sako, Baturaja',
    nominalSPP: 250000,
    tanggalLahir: '24-12-2015',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-06', transactionId: 't-spp3' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-05', transactionId: 't-spp4' },
      'September 2026': { paid: true, paidAt: '2026-09-02', transactionId: 't-spp5' },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's3',
    nis: '20261003',
    nama: 'Muhammad Azzam',
    kelas: '4-B',
    namaOrangTua: 'Irfan Hakim',
    noWhatsApp: '6285273114400',
    alamat: 'Perumnas Kenten Kentang Raya Gg. Kelapa Gading No. 12',
    nominalSPP: 275000,
    tanggalLahir: '11-03-2014',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-05', transactionId: 't-spp6' },
      'Agustus 2026': { paid: false },
      'September 2026': { paid: false },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's4',
    nis: '20261004',
    nama: 'Syifa Nurul Khatimah',
    kelas: '5-B',
    namaOrangTua: 'Rahmat Hidayat',
    noWhatsApp: '6287890902312',
    alamat: 'Komplek Pusri Sako Jl. Anggrek II No. 8',
    nominalSPP: 275000,
    tanggalLahir: '05-09-2013',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-08', transactionId: 't-spp7' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-09', transactionId: 't-spp8' },
      'September 2026': { paid: true, paidAt: '2026-09-08', transactionId: 't-spp9' },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's5',
    nis: '20261005',
    nama: 'Fatimah Az-Zahra',
    kelas: '1-A',
    namaOrangTua: 'Ridwan Kamil',
    noWhatsApp: '6289945452233',
    alamat: 'Semat Borang Jl. Karya Bersama Raya Blok E-5',
    nominalSPP: 250000,
    tanggalLahir: '15-08-2017',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-10', transactionId: 't-spp10' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-11', transactionId: 't-spp11' },
      'September 2026': { paid: false },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's6',
    nis: '20261006',
    nama: 'Zikri Al-Buchori',
    kelas: '2-A',
    namaOrangTua: 'Supriyadi',
    noWhatsApp: '6281211223344',
    alamat: 'Kenten Laut Permai Lorong Sejahtera No. 15',
    nominalSPP: 250000,
    tanggalLahir: '20-10-2016',
    statusSPP: {
      'Juli 2026': { paid: false },
      'Agustus 2026': { paid: false },
      'September 2026': { paid: false },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's7',
    nis: '20261007',
    nama: 'Hanif Shofwan',
    kelas: '6-A',
    namaOrangTua: 'Agus Subarjo',
    noWhatsApp: '6281312345678',
    alamat: 'Jl. Sumpah Pemuda Gg. Harapan No. 3 RT 012/RW 001',
    nominalSPP: 300000,
    tanggalLahir: '30-01-2011',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-02', transactionId: 't-spp12' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-02', transactionId: 't-spp13' },
      'September 2026': { paid: true, paidAt: '2026-09-02', transactionId: 't-spp14' },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
  {
    id: 's8',
    nis: '20261008',
    nama: 'Nabila Zahra',
    kelas: '6-B',
    namaOrangTua: 'Heru Trianto',
    noWhatsApp: '6282122334455',
    alamat: 'Perumahan Bukit Sejahtera Blok G-09, Baturaja',
    nominalSPP: 300000,
    tanggalLahir: '14-02-2011',
    statusSPP: {
      'Juli 2026': { paid: true, paidAt: '2026-07-06', transactionId: 't-spp15' },
      'Agustus 2026': { paid: true, paidAt: '2026-08-04', transactionId: 't-spp16' },
      'September 2026': { paid: false },
      'Oktober 2026': { paid: false },
      'November 2026': { paid: false },
      'Desember 2026': { paid: false },
      'Januari 2027': { paid: false },
      'Februari 2027': { paid: false },
      'Maret 2027': { paid: false },
      'April 2027': { paid: false },
      'Mei 2027': { paid: false },
      'Juni 2027': { paid: false },
    },
  },
];

export const INITIAL_TRANSAKSI: TransaksiKas[] = [
  {
    id: 't-spp1',
    tanggal: '2026-07-05',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Ahmad Rafif Al-Fatih (3-A)',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp2',
    tanggal: '2026-08-04',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Ahmad Rafif Al-Fatih (3-A)',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp3',
    tanggal: '2026-07-06',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Aisyah Humaira (3-A)',
    siswaId: 's2',
    siswaNama: 'Aisyah Humaira',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp4',
    tanggal: '2026-08-05',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Aisyah Humaira (3-A)',
    siswaId: 's2',
    siswaNama: 'Aisyah Humaira',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp5',
    tanggal: '2026-09-02',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan September 2026 - Aisyah Humaira (3-A)',
    siswaId: 's2',
    siswaNama: 'Aisyah Humaira',
    bulanSPP: 'September 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp6',
    tanggal: '2026-07-05',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 275000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Muhammad Azzam (4-B)',
    siswaId: 's3',
    siswaNama: 'Muhammad Azzam',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp7',
    tanggal: '2026-07-08',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 275000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Syifa Nurul Khatimah (5-B)',
    siswaId: 's4',
    siswaNama: 'Syifa Nurul Khatimah',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp8',
    tanggal: '2026-08-09',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 275000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Syifa Nurul Khatimah (5-B)',
    siswaId: 's4',
    siswaNama: 'Syifa Nurul Khatimah',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp9',
    tanggal: '2026-09-08',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 275000,
    keterangan: 'Pembayaran SPP Bulan September 2026 - Syifa Nurul Khatimah (5-B)',
    siswaId: 's4',
    siswaNama: 'Syifa Nurul Khatimah',
    bulanSPP: 'September 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp10',
    tanggal: '2026-07-10',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Fatimah Az-Zahra (1-A)',
    siswaId: 's5',
    siswaNama: 'Fatimah Az-Zahra',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp11',
    tanggal: '2026-08-11',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 250000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Fatimah Az-Zahra (1-A)',
    siswaId: 's5',
    siswaNama: 'Fatimah Az-Zahra',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp12',
    tanggal: '2026-07-02',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 300000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Hanif Shofwan (6-A)',
    siswaId: 's7',
    siswaNama: 'Hanif Shofwan',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp13',
    tanggal: '2026-08-02',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 300000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Hanif Shofwan (6-A)',
    siswaId: 's7',
    siswaNama: 'Hanif Shofwan',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp14',
    tanggal: '2026-09-02',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 300000,
    keterangan: 'Pembayaran SPP Bulan September 2026 - Hanif Shofwan (6-A)',
    siswaId: 's7',
    siswaNama: 'Hanif Shofwan',
    bulanSPP: 'September 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-spp15',
    tanggal: '2026-07-06',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 300000,
    keterangan: 'Pembayaran SPP Bulan Juli 2026 - Nabila Zahra (6-B)',
    siswaId: 's8',
    siswaNama: 'Nabila Zahra',
    bulanSPP: 'Juli 2026',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-spp16',
    tanggal: '2026-08-04',
    tipe: 'pemasukan',
    kategori: 'SPP Bulanan',
    nominal: 300000,
    keterangan: 'Pembayaran SPP Bulan Agustus 2026 - Nabila Zahra (6-B)',
    siswaId: 's8',
    siswaNama: 'Nabila Zahra',
    bulanSPP: 'Agustus 2026',
    metodePembayaran: 'Tunai',
  },
  // Dana BOS & Lainnya
  {
    id: 't-non1',
    tanggal: '2026-07-01',
    tipe: 'pemasukan',
    kategori: 'Dana BOS',
    nominal: 45000000,
    keterangan: 'Pencairan Dana BOS Tahap II 2026 SDIT Al Fatih',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-non2',
    tanggal: '2026-07-15',
    tipe: 'pemasukan',
    kategori: 'Donasi / Infaq',
    nominal: 2500000,
    keterangan: 'Infaq Sarpras dari Yayasan Khalifah Generasi Cemerlang',
    metodePembayaran: 'Tunai',
  },
  // Pengeluaran
  {
    id: 't-out1',
    tanggal: '2026-07-25',
    tipe: 'pengeluaran',
    kategori: 'Gaji Guru & Staff',
    nominal: 18500000,
    keterangan: 'Gaji Bulanan Guru Honorer & Staff TU (7 Orang) Juli 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-out2',
    tanggal: '2026-07-10',
    tipe: 'pengeluaran',
    kategori: 'Operasional Listrik & Wifi',
    nominal: 1250000,
    keterangan: 'Pembayaran Wifi Indihome & Listrik Token Sekolah',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-out3',
    tanggal: '2026-07-12',
    tipe: 'pengeluaran',
    kategori: 'ATK & Kebutuhan Kantor',
    nominal: 680000,
    keterangan: 'Membeli Kertas A4, Spidol Boardmarker, dan Buku Kas Kelas',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-out4',
    tanggal: '2026-07-28',
    tipe: 'pengeluaran',
    kategori: 'Pemeliharaan Gedung & Sarpras',
    nominal: 3500000,
    keterangan: 'Renovasi Genteng Bocor Ruang Kelas 1 & Pengecatan Kursi Siswa',
    metodePembayaran: 'Tunai',
  },
  {
    id: 't-out5',
    tanggal: '2026-08-25',
    tipe: 'pengeluaran',
    kategori: 'Gaji Guru & Staff',
    nominal: 18500000,
    keterangan: 'Gaji Bulanan Guru Honorer & Staff TU Agustus 2026',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-out6',
    tanggal: '2026-08-10',
    tipe: 'pengeluaran',
    kategori: 'Operasional Listrik & Wifi',
    nominal: 1320000,
    keterangan: 'Tagihan Listrik PLN & Wifi Bulanan Pascabayar',
    metodePembayaran: 'Transfer Bank',
  },
  {
    id: 't-out7',
    tanggal: '2026-08-17',
    tipe: 'pengeluaran',
    kategori: 'Biaya Kegiatan & Lomba',
    nominal: 4500000,
    keterangan: 'Biaya Lomba & Hadiah Pesta Kemerdekaan RI Ke-81',
    metodePembayaran: 'Tunai',
  },
];

export const INITIAL_WA_LOGS: WhatsAppLog[] = [
  {
    id: 'wal1',
    timestamp: '2026-07-05 09:12:30',
    studentName: 'Ahmad Rafif Al-Fatih',
    parentName: 'Hendra Wijaya',
    recipientPhone: '6281273849201',
    message: '*SDIT AL FATIH - KONFIRMASI PEMBAYARAN*\n\nAlhamdulillah, terima kasih. Pembayaran SPP untuk siswa/i *Ahmad Rafif Al-Fatih* (Kelas 3-A) untuk *Juli 2026* sebesar *Rp 250.000* Telah berhasil diterima.\n\n_Metode: Tunai_\n_Tanggal: 2026-07-05_\n\nSemoga menjadi berkah dan mempermudah kelancaran belajar putra/i Bapak/Ibu. Jazakumullahu Khairan.',
    status: 'Terkirim',
    type: 'Pembayaran SPP',
  },
  {
    id: 'wal2',
    timestamp: '2026-07-06 14:30:15',
    studentName: 'Aisyah Humaira',
    parentName: 'Budi Santoso',
    recipientPhone: '6281367895432',
    message: '*SDIT AL FATIH - KONFIRMASI PEMBAYARAN*\n\nAlhamdulillah, terima kasih. Pembayaran SPP untuk siswa/i *Aisyah Humaira* (Kelas 3-A) untuk *Juli 2026* sebesar *Rp 250.000* Telah berhasil diterima.\n\n_Metode: Transfer Bank_\n_Tanggal: 2026-07-06_\n\nSemoga menjadi berkah dan mempermudah kelancaran belajar putra/i Bapak/Ibu. Jazakumullahu Khairan.',
    status: 'Terkirim',
    type: 'Pembayaran SPP',
  },
  {
    id: 'wal3',
    timestamp: '2026-08-04 10:05:44',
    studentName: 'Ahmad Rafif Al-Fatih',
    parentName: 'Hendra Wijaya',
    recipientPhone: '6281273849201',
    message: '*SDIT AL FATIH - KONFIRMASI PEMBAYARAN*\n\nAlhamdulillah, terima kasih. Pembayaran SPP untuk siswa/i *Ahmad Rafif Al-Fatih* (Kelas 3-A) untuk *Agustus 2026* sebesar *Rp 250.000* Telah berhasil diterima.\n\n_Metode: Tunai_\n_Tanggal: 2026-08-04_\n\nSemoga menjadi berkah dan mempermudah kelancaran belajar putra/i Bapak/Ibu. Jazakumullahu Khairan.',
    status: 'Terkirim',
    type: 'Pembayaran SPP',
  },
];

export const INITIAL_TABUNGAN_TRANSACTIONS = [
  {
    id: 'tab-1',
    tanggal: '2026-07-01 08:30:00',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    siswaKelas: '3-A',
    tipe: 'setor' as const,
    nominal: 150000,
    keterangan: 'Setoran Awal Buku Tabungan Baru',
    petugasNama: 'Nurhaliza S.Pd',
    adminApproved: true,
  },
  {
    id: 'tab-2',
    tanggal: '2026-07-02 09:15:00',
    siswaId: 's2',
    siswaNama: 'Aisyah Humaira',
    siswaKelas: '3-A',
    tipe: 'setor' as const,
    nominal: 500000,
    keterangan: 'Titipan Tabungan Bulanan Orang Tua',
    petugasNama: 'Nurhaliza S.Pd',
    adminApproved: true,
  },
  {
    id: 'tab-3',
    tanggal: '2026-07-03 10:00:00',
    siswaId: 's3',
    siswaNama: 'Muhammad Azzam',
    siswaKelas: '4-B',
    tipe: 'setor' as const,
    nominal: 200000,
    keterangan: 'Setoran Tunai Mingguan',
    petugasNama: 'Ahmad Dahlan',
    adminApproved: true,
  },
  {
    id: 'tab-4',
    tanggal: '2026-07-08 08:45:00',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    siswaKelas: '3-A',
    tipe: 'setor' as const,
    nominal: 50000,
    keterangan: 'Sisa Uang Jajan Masuk Tabungan',
    petugasNama: 'Nurhaliza S.Pd',
    adminApproved: true,
  },
  {
    id: 'tab-5',
    tanggal: '2026-07-12 11:30:00',
    siswaId: 's3',
    siswaNama: 'Muhammad Azzam',
    siswaKelas: '4-B',
    tipe: 'tarik' as const,
    nominal: 100000,
    keterangan: 'Tarik Tunai Beli Buku Tulis Tambahan',
    petugasNama: 'Nurhaliza S.Pd',
    adminApproved: true,
  },
  {
    id: 'tab-6',
    tanggal: '2026-07-15 09:40:00',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    siswaKelas: '3-A',
    tipe: 'tarik' as const,
    nominal: 30000,
    keterangan: 'Keperluan Belanja Koperasi Sekolah',
    petugasNama: 'Nurhaliza S.Pd',
    adminApproved: true,
  },
];

export const INITIAL_MIDTRANS_TRANSACTIONS = [
  {
    id: 'order-spp-1781298374987',
    tanggal: '2026-06-18 08:30',
    siswaId: 's1',
    siswaNama: 'Ahmad Rafif Al-Fatih',
    siswaNis: '20261001',
    siswaKelas: '3-A',
    parentName: 'Hendra Wijaya',
    parentPhone: '6281273849201',
    amount: 250000,
    months: ['September 2026'],
    notes: 'Bayar lewat Midtrans Sandbox GoPay',
    status: 'pending_verification' as const,
    paymentMethodDetails: 'GoPay',
    snapToken: 'simulated_snap_token_1'
  },
  {
    id: 'order-spp-1781298312093',
    tanggal: '2026-06-17 14:20',
    siswaId: 's3',
    siswaNama: 'Muhammad Azzam',
    siswaNis: '20261003',
    siswaKelas: '4-B',
    parentName: 'Rudi Hermawan', // parent of Azzam
    parentPhone: '6285273948201',
    amount: 250000,
    months: ['Juli 2026'],
    notes: 'Transfer Virtual Account BSI',
    status: 'verified' as const,
    paymentMethodDetails: 'BSI Virtual Account',
    snapToken: 'simulated_snap_token_2',
    verifiedAt: '2026-06-17 15:00',
    verifiedBy: 'Ustazah Admin Keuangan'
  }
];


